export const content = [
  '# Heading 1',
  '## Heading 2',
  '### Heading 3',
  '#### Heading 4',
  '##### Heading 5',
  '###### Heading 6',
  '',
  '**bold**',
  '*italic*',
  '~~strikethrough~~',
  '',
  '> blockquote',
  '',
  '* list item 1',
  '* list item 2',
  '* list item 3',
  '',
  '1. ordered list item 1',
  '2. ordered list item 2',
  '3. ordered list item 3',
  '',
  '`inline code`',
  '',
  '[link](https://example.com)',
  '',
  '| @cols=2:merged |',
  '| --- | --- |',
  '| table | table |',
].join('\n');
